// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sensors/huawei-twamp-controller/huawei-twamp-controller.proto

package huawei_twamp_controller

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TwampController_Client_Sessions_Session_PaddingType int32

const (
	TwampController_Client_Sessions_Session_PaddingType_X_00 TwampController_Client_Sessions_Session_PaddingType = 0
	TwampController_Client_Sessions_Session_PaddingType_X_55 TwampController_Client_Sessions_Session_PaddingType = 85
	TwampController_Client_Sessions_Session_PaddingType_AA   TwampController_Client_Sessions_Session_PaddingType = 170
	TwampController_Client_Sessions_Session_PaddingType_FF   TwampController_Client_Sessions_Session_PaddingType = 255
)

var TwampController_Client_Sessions_Session_PaddingType_name = map[int32]string{
	0:   "PaddingType_X_00",
	85:  "PaddingType_X_55",
	170: "PaddingType_AA",
	255: "PaddingType_FF",
}

var TwampController_Client_Sessions_Session_PaddingType_value = map[string]int32{
	"PaddingType_X_00": 0,
	"PaddingType_X_55": 85,
	"PaddingType_AA":   170,
	"PaddingType_FF":   255,
}

func (x TwampController_Client_Sessions_Session_PaddingType) String() string {
	return proto.EnumName(TwampController_Client_Sessions_Session_PaddingType_name, int32(x))
}

func (TwampController_Client_Sessions_Session_PaddingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 0, 0, 0, 0}
}

type TwampController struct {
	Client               *TwampController_Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Sender               *TwampController_Sender `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TwampController) Reset()         { *m = TwampController{} }
func (m *TwampController) String() string { return proto.CompactTextString(m) }
func (*TwampController) ProtoMessage()    {}
func (*TwampController) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0}
}

func (m *TwampController) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController.Unmarshal(m, b)
}
func (m *TwampController) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController.Marshal(b, m, deterministic)
}
func (m *TwampController) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController.Merge(m, src)
}
func (m *TwampController) XXX_Size() int {
	return xxx_messageInfo_TwampController.Size(m)
}
func (m *TwampController) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController proto.InternalMessageInfo

func (m *TwampController) GetClient() *TwampController_Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *TwampController) GetSender() *TwampController_Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

type TwampController_Client struct {
	Sessions             *TwampController_Client_Sessions `protobuf:"bytes,1,opt,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TwampController_Client) Reset()         { *m = TwampController_Client{} }
func (m *TwampController_Client) String() string { return proto.CompactTextString(m) }
func (*TwampController_Client) ProtoMessage()    {}
func (*TwampController_Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 0}
}

func (m *TwampController_Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController_Client.Unmarshal(m, b)
}
func (m *TwampController_Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController_Client.Marshal(b, m, deterministic)
}
func (m *TwampController_Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController_Client.Merge(m, src)
}
func (m *TwampController_Client) XXX_Size() int {
	return xxx_messageInfo_TwampController_Client.Size(m)
}
func (m *TwampController_Client) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController_Client.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController_Client proto.InternalMessageInfo

func (m *TwampController_Client) GetSessions() *TwampController_Client_Sessions {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type TwampController_Client_Sessions struct {
	Session              []*TwampController_Client_Sessions_Session `protobuf:"bytes,1,rep,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *TwampController_Client_Sessions) Reset()         { *m = TwampController_Client_Sessions{} }
func (m *TwampController_Client_Sessions) String() string { return proto.CompactTextString(m) }
func (*TwampController_Client_Sessions) ProtoMessage()    {}
func (*TwampController_Client_Sessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 0, 0}
}

func (m *TwampController_Client_Sessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController_Client_Sessions.Unmarshal(m, b)
}
func (m *TwampController_Client_Sessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController_Client_Sessions.Marshal(b, m, deterministic)
}
func (m *TwampController_Client_Sessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController_Client_Sessions.Merge(m, src)
}
func (m *TwampController_Client_Sessions) XXX_Size() int {
	return xxx_messageInfo_TwampController_Client_Sessions.Size(m)
}
func (m *TwampController_Client_Sessions) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController_Client_Sessions.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController_Client_Sessions proto.InternalMessageInfo

func (m *TwampController_Client_Sessions) GetSession() []*TwampController_Client_Sessions_Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type TwampController_Client_Sessions_Session struct {
	Id                   uint32                                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SendIpAddr           string                                              `protobuf:"bytes,2,opt,name=send_ip_addr,json=send-ip-addr,proto3" json:"send_ip_addr,omitempty"`
	RefIpAddr            string                                              `protobuf:"bytes,3,opt,name=ref_ip_addr,json=ref-ip-addr,proto3" json:"ref_ip_addr,omitempty"`
	SendPort             uint32                                              `protobuf:"varint,4,opt,name=send_port,json=send-port,proto3" json:"send_port,omitempty"`
	RefPort              uint32                                              `protobuf:"varint,5,opt,name=ref_port,json=ref-port,proto3" json:"ref_port,omitempty"`
	VrfName              string                                              `protobuf:"bytes,6,opt,name=vrf_name,json=vrf-name,proto3" json:"vrf_name,omitempty"`
	DscpValue            uint32                                              `protobuf:"varint,7,opt,name=dscp_value,json=dscp-value,proto3" json:"dscp_value,omitempty"`
	PaddingLength        uint32                                              `protobuf:"varint,8,opt,name=padding_length,json=padding-length,proto3" json:"padding_length,omitempty"`
	PaddingType          TwampController_Client_Sessions_Session_PaddingType `protobuf:"varint,9,opt,name=padding_type,json=padding-type,proto3,enum=huawei_twamp_controller.TwampController_Client_Sessions_Session_PaddingType" json:"padding_type,omitempty"`
	Description          string                                              `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Statistics           *TwampController_Client_Sessions_Session_Statistics `protobuf:"bytes,11,opt,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                            `json:"-"`
	XXX_unrecognized     []byte                                              `json:"-"`
	XXX_sizecache        int32                                               `json:"-"`
}

func (m *TwampController_Client_Sessions_Session) Reset() {
	*m = TwampController_Client_Sessions_Session{}
}
func (m *TwampController_Client_Sessions_Session) String() string { return proto.CompactTextString(m) }
func (*TwampController_Client_Sessions_Session) ProtoMessage()    {}
func (*TwampController_Client_Sessions_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 0, 0, 0}
}

func (m *TwampController_Client_Sessions_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController_Client_Sessions_Session.Unmarshal(m, b)
}
func (m *TwampController_Client_Sessions_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController_Client_Sessions_Session.Marshal(b, m, deterministic)
}
func (m *TwampController_Client_Sessions_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController_Client_Sessions_Session.Merge(m, src)
}
func (m *TwampController_Client_Sessions_Session) XXX_Size() int {
	return xxx_messageInfo_TwampController_Client_Sessions_Session.Size(m)
}
func (m *TwampController_Client_Sessions_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController_Client_Sessions_Session.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController_Client_Sessions_Session proto.InternalMessageInfo

func (m *TwampController_Client_Sessions_Session) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session) GetSendIpAddr() string {
	if m != nil {
		return m.SendIpAddr
	}
	return ""
}

func (m *TwampController_Client_Sessions_Session) GetRefIpAddr() string {
	if m != nil {
		return m.RefIpAddr
	}
	return ""
}

func (m *TwampController_Client_Sessions_Session) GetSendPort() uint32 {
	if m != nil {
		return m.SendPort
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session) GetRefPort() uint32 {
	if m != nil {
		return m.RefPort
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *TwampController_Client_Sessions_Session) GetDscpValue() uint32 {
	if m != nil {
		return m.DscpValue
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session) GetPaddingLength() uint32 {
	if m != nil {
		return m.PaddingLength
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session) GetPaddingType() TwampController_Client_Sessions_Session_PaddingType {
	if m != nil {
		return m.PaddingType
	}
	return TwampController_Client_Sessions_Session_PaddingType_X_00
}

func (m *TwampController_Client_Sessions_Session) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TwampController_Client_Sessions_Session) GetStatistics() *TwampController_Client_Sessions_Session_Statistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

type TwampController_Client_Sessions_Session_Statistics struct {
	AvgDelay             uint32   `protobuf:"varint,1,opt,name=avg_delay,json=avg-delay,proto3" json:"avg_delay,omitempty"`
	AvgJitter            uint32   `protobuf:"varint,2,opt,name=avg_jitter,json=avg-jitter,proto3" json:"avg_jitter,omitempty"`
	LossCount            uint32   `protobuf:"varint,3,opt,name=loss_count,json=loss-count,proto3" json:"loss_count,omitempty"`
	SendCount            uint32   `protobuf:"varint,4,opt,name=send_count,json=send-count,proto3" json:"send_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwampController_Client_Sessions_Session_Statistics) Reset() {
	*m = TwampController_Client_Sessions_Session_Statistics{}
}
func (m *TwampController_Client_Sessions_Session_Statistics) String() string {
	return proto.CompactTextString(m)
}
func (*TwampController_Client_Sessions_Session_Statistics) ProtoMessage() {}
func (*TwampController_Client_Sessions_Session_Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 0, 0, 0, 0}
}

func (m *TwampController_Client_Sessions_Session_Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics.Unmarshal(m, b)
}
func (m *TwampController_Client_Sessions_Session_Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics.Marshal(b, m, deterministic)
}
func (m *TwampController_Client_Sessions_Session_Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics.Merge(m, src)
}
func (m *TwampController_Client_Sessions_Session_Statistics) XXX_Size() int {
	return xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics.Size(m)
}
func (m *TwampController_Client_Sessions_Session_Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController_Client_Sessions_Session_Statistics proto.InternalMessageInfo

func (m *TwampController_Client_Sessions_Session_Statistics) GetAvgDelay() uint32 {
	if m != nil {
		return m.AvgDelay
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session_Statistics) GetAvgJitter() uint32 {
	if m != nil {
		return m.AvgJitter
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session_Statistics) GetLossCount() uint32 {
	if m != nil {
		return m.LossCount
	}
	return 0
}

func (m *TwampController_Client_Sessions_Session_Statistics) GetSendCount() uint32 {
	if m != nil {
		return m.SendCount
	}
	return 0
}

type TwampController_Sender struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwampController_Sender) Reset()         { *m = TwampController_Sender{} }
func (m *TwampController_Sender) String() string { return proto.CompactTextString(m) }
func (*TwampController_Sender) ProtoMessage()    {}
func (*TwampController_Sender) Descriptor() ([]byte, []int) {
	return fileDescriptor_200b3ab98d607960, []int{0, 1}
}

func (m *TwampController_Sender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwampController_Sender.Unmarshal(m, b)
}
func (m *TwampController_Sender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwampController_Sender.Marshal(b, m, deterministic)
}
func (m *TwampController_Sender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwampController_Sender.Merge(m, src)
}
func (m *TwampController_Sender) XXX_Size() int {
	return xxx_messageInfo_TwampController_Sender.Size(m)
}
func (m *TwampController_Sender) XXX_DiscardUnknown() {
	xxx_messageInfo_TwampController_Sender.DiscardUnknown(m)
}

var xxx_messageInfo_TwampController_Sender proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("huawei_twamp_controller.TwampController_Client_Sessions_Session_PaddingType", TwampController_Client_Sessions_Session_PaddingType_name, TwampController_Client_Sessions_Session_PaddingType_value)
	proto.RegisterType((*TwampController)(nil), "huawei_twamp_controller.TwampController")
	proto.RegisterType((*TwampController_Client)(nil), "huawei_twamp_controller.TwampController.Client")
	proto.RegisterType((*TwampController_Client_Sessions)(nil), "huawei_twamp_controller.TwampController.Client.Sessions")
	proto.RegisterType((*TwampController_Client_Sessions_Session)(nil), "huawei_twamp_controller.TwampController.Client.Sessions.Session")
	proto.RegisterType((*TwampController_Client_Sessions_Session_Statistics)(nil), "huawei_twamp_controller.TwampController.Client.Sessions.Session.Statistics")
	proto.RegisterType((*TwampController_Sender)(nil), "huawei_twamp_controller.TwampController.Sender")
}

func init() {
	proto.RegisterFile("proto/sensors/huawei-twamp-controller/huawei-twamp-controller.proto", fileDescriptor_200b3ab98d607960)
}

var fileDescriptor_200b3ab98d607960 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x71, 0x4a, 0x1d, 0xe7, 0xa5, 0x09, 0xd1, 0x80, 0x84, 0x65, 0x21, 0x14, 0x65, 0x81,
	0xb2, 0x19, 0xa7, 0x0a, 0xaa, 0xc4, 0x92, 0x2a, 0x52, 0x59, 0xc0, 0x02, 0x39, 0x41, 0x42, 0x6c,
	0x46, 0xc6, 0x33, 0x4d, 0x07, 0x5c, 0x7b, 0xe4, 0x99, 0xa4, 0xca, 0x15, 0x38, 0x0a, 0x47, 0xe0,
	0x26, 0x5c, 0x81, 0x15, 0x37, 0x00, 0xcd, 0x1b, 0xdb, 0x8d, 0x8a, 0xba, 0x28, 0xdd, 0xe5, 0x7d,
	0xff, 0xfb, 0xff, 0x19, 0x3f, 0x3f, 0x07, 0x16, 0xaa, 0x2a, 0x4d, 0x39, 0xd3, 0xa2, 0xd0, 0x65,
	0xa5, 0x67, 0x17, 0x9b, 0xf4, 0x4a, 0x48, 0x6a, 0xae, 0xd2, 0x4b, 0x45, 0xb3, 0xb2, 0x30, 0x55,
	0x99, 0xe7, 0xa2, 0xba, 0x8d, 0xc7, 0xe8, 0x26, 0x4f, 0x9d, 0xcc, 0x50, 0x66, 0xd7, 0xf2, 0xe4,
	0x57, 0x00, 0x8f, 0x56, 0x16, 0x2e, 0x5a, 0x46, 0xde, 0x80, 0x9f, 0xe5, 0x52, 0x14, 0x26, 0xf4,
	0xc6, 0xde, 0xb4, 0x3f, 0x9f, 0xc5, 0xb7, 0xb8, 0xe3, 0x1b, 0xce, 0x78, 0x81, 0xb6, 0xa4, 0xb6,
	0xdb, 0x20, 0x2d, 0x0a, 0x2e, 0xaa, 0xb0, 0x73, 0xc7, 0xa0, 0x25, 0xda, 0x92, 0xda, 0x1e, 0xfd,
	0xe8, 0x82, 0xef, 0xb2, 0xc9, 0x0a, 0x02, 0x2d, 0xb4, 0x96, 0x65, 0xa1, 0xeb, 0xeb, 0xbd, 0xba,
	0xe3, 0xf5, 0xe2, 0x65, 0xed, 0x4f, 0xda, 0xa4, 0xe8, 0xa7, 0x0f, 0x41, 0x83, 0xc9, 0x27, 0xe8,
	0xd6, 0x42, 0xe8, 0x8d, 0x0f, 0xa6, 0xfd, 0xf9, 0xeb, 0xff, 0x3d, 0xa1, 0xf9, 0x91, 0x34, 0x81,
	0xd1, 0xef, 0x43, 0xe8, 0xd6, 0x90, 0x0c, 0xa1, 0x23, 0x39, 0x3e, 0xc4, 0x20, 0xe9, 0x48, 0x4e,
	0x26, 0x70, 0x64, 0x9f, 0x97, 0x49, 0xc5, 0x52, 0xce, 0xdd, 0xd0, 0x7a, 0x09, 0x32, 0x2a, 0x15,
	0xb5, 0x8c, 0x8c, 0xa1, 0x5f, 0x89, 0xf3, 0xb6, 0xe5, 0x00, 0x5b, 0x2c, 0x6a, 0x3b, 0x9e, 0x41,
	0x0f, 0x53, 0x54, 0x59, 0x99, 0xf0, 0x21, 0x86, 0x23, 0xa0, 0x16, 0x90, 0x08, 0x02, 0xeb, 0x47,
	0xf1, 0x10, 0x45, 0x5b, 0xb7, 0xda, 0xb6, 0x3a, 0x67, 0x45, 0x7a, 0x29, 0x42, 0x1f, 0x83, 0x6d,
	0x4d, 0x6d, 0x4d, 0x9e, 0x03, 0x70, 0x9d, 0x29, 0xb6, 0x4d, 0xf3, 0x8d, 0x08, 0xbb, 0xe8, 0x44,
	0x42, 0x91, 0x90, 0x17, 0x30, 0x54, 0x29, 0xe7, 0xb2, 0x58, 0xb3, 0x5c, 0x14, 0x6b, 0x73, 0x11,
	0x06, 0xd8, 0xd3, 0x50, 0xea, 0x28, 0x51, 0x70, 0xd4, 0xf4, 0x99, 0x9d, 0x12, 0x61, 0x6f, 0xec,
	0x4d, 0x87, 0xf3, 0x77, 0xf7, 0x1d, 0x70, 0xfc, 0xde, 0x85, 0xae, 0x76, 0x4a, 0x24, 0xcd, 0x09,
	0xd4, 0x9e, 0x60, 0x27, 0xc6, 0x85, 0xce, 0x2a, 0xa9, 0x8c, 0x7d, 0xa3, 0xe0, 0x26, 0xb6, 0x87,
	0xc8, 0x57, 0x00, 0x6d, 0x52, 0x23, 0xb5, 0x91, 0x99, 0x0e, 0xfb, 0xb8, 0x54, 0x6f, 0xef, 0x7d,
	0xa3, 0x65, 0x1b, 0x99, 0xec, 0xc5, 0x47, 0xdf, 0x3c, 0x80, 0x6b, 0xc9, 0xbe, 0xad, 0x74, 0xbb,
	0x66, 0x5c, 0xe4, 0xe9, 0xae, 0x5e, 0x05, 0x0b, 0x28, 0x02, 0x3b, 0x75, 0xab, 0x7e, 0x91, 0xc6,
	0xd4, 0x1f, 0xd1, 0x20, 0xb1, 0x84, 0x3a, 0x62, 0xf5, 0xbc, 0xd4, 0x9a, 0x65, 0xe5, 0xa6, 0x30,
	0xb8, 0x0c, 0x83, 0x04, 0x09, 0x45, 0x62, 0x75, 0xdc, 0x05, 0xa7, 0xbb, 0x65, 0x40, 0xe2, 0xf4,
	0x49, 0x06, 0xfd, 0xbd, 0xc1, 0x91, 0x27, 0x30, 0xda, 0x2b, 0xd9, 0x47, 0x76, 0x7c, 0x3c, 0x7a,
	0xf0, 0x2f, 0x3d, 0x39, 0x19, 0x7d, 0x20, 0x8f, 0x61, 0xb8, 0x4f, 0x4f, 0x4f, 0x47, 0xdf, 0xbd,
	0x9b, 0xf0, 0xec, 0x6c, 0xf4, 0xc7, 0x8b, 0x02, 0xf0, 0xdd, 0xe7, 0xfc, 0xd9, 0xc7, 0x3f, 0xa3,
	0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xf1, 0x84, 0x82, 0xd3, 0x04, 0x00, 0x00,
}
