// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/huawei-dialin/huawei-grpc-dialin.proto

package huawei_dialin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Path struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_c059edd071d94e03, []int{0}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SubsArgs struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Encoding             uint32   `protobuf:"varint,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Path                 []*Path  `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	SampleInterval       uint64   `protobuf:"varint,6,opt,name=sample_interval,json=sampleInterval,proto3" json:"sample_interval,omitempty"`
	HeartbeatInterval    uint64   `protobuf:"varint,7,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	SuppressRedundant    bool     `protobuf:"varint,8,opt,name=suppress_redundant,json=suppressRedundant,proto3" json:"suppress_redundant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubsArgs) Reset()         { *m = SubsArgs{} }
func (m *SubsArgs) String() string { return proto.CompactTextString(m) }
func (*SubsArgs) ProtoMessage()    {}
func (*SubsArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c059edd071d94e03, []int{1}
}

func (m *SubsArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubsArgs.Unmarshal(m, b)
}
func (m *SubsArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubsArgs.Marshal(b, m, deterministic)
}
func (m *SubsArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsArgs.Merge(m, src)
}
func (m *SubsArgs) XXX_Size() int {
	return xxx_messageInfo_SubsArgs.Size(m)
}
func (m *SubsArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsArgs.DiscardUnknown(m)
}

var xxx_messageInfo_SubsArgs proto.InternalMessageInfo

func (m *SubsArgs) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *SubsArgs) GetEncoding() uint32 {
	if m != nil {
		return m.Encoding
	}
	return 0
}

func (m *SubsArgs) GetPath() []*Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *SubsArgs) GetSampleInterval() uint64 {
	if m != nil {
		return m.SampleInterval
	}
	return 0
}

func (m *SubsArgs) GetHeartbeatInterval() uint64 {
	if m != nil {
		return m.HeartbeatInterval
	}
	return 0
}

func (m *SubsArgs) GetSuppressRedundant() bool {
	if m != nil {
		return m.SuppressRedundant
	}
	return false
}

type SubsReply struct {
	SubscriptionId uint32 `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	RequestId      uint64 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseCode   string `protobuf:"bytes,3,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	// Types that are valid to be assigned to MessageData:
	//	*SubsReply_Message
	//	*SubsReply_MessageJson
	MessageData          isSubsReply_MessageData `protobuf_oneof:"MessageData"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SubsReply) Reset()         { *m = SubsReply{} }
func (m *SubsReply) String() string { return proto.CompactTextString(m) }
func (*SubsReply) ProtoMessage()    {}
func (*SubsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c059edd071d94e03, []int{2}
}

func (m *SubsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubsReply.Unmarshal(m, b)
}
func (m *SubsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubsReply.Marshal(b, m, deterministic)
}
func (m *SubsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubsReply.Merge(m, src)
}
func (m *SubsReply) XXX_Size() int {
	return xxx_messageInfo_SubsReply.Size(m)
}
func (m *SubsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubsReply proto.InternalMessageInfo

func (m *SubsReply) GetSubscriptionId() uint32 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

func (m *SubsReply) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *SubsReply) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

type isSubsReply_MessageData interface {
	isSubsReply_MessageData()
}

type SubsReply_Message struct {
	Message []byte `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type SubsReply_MessageJson struct {
	MessageJson string `protobuf:"bytes,5,opt,name=message_json,json=messageJson,proto3,oneof"`
}

func (*SubsReply_Message) isSubsReply_MessageData() {}

func (*SubsReply_MessageJson) isSubsReply_MessageData() {}

func (m *SubsReply) GetMessageData() isSubsReply_MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *SubsReply) GetMessage() []byte {
	if x, ok := m.GetMessageData().(*SubsReply_Message); ok {
		return x.Message
	}
	return nil
}

func (m *SubsReply) GetMessageJson() string {
	if x, ok := m.GetMessageData().(*SubsReply_MessageJson); ok {
		return x.MessageJson
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubsReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubsReply_Message)(nil),
		(*SubsReply_MessageJson)(nil),
	}
}

type CancelArgs struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SubscriptionId       uint32   `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelArgs) Reset()         { *m = CancelArgs{} }
func (m *CancelArgs) String() string { return proto.CompactTextString(m) }
func (*CancelArgs) ProtoMessage()    {}
func (*CancelArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c059edd071d94e03, []int{3}
}

func (m *CancelArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelArgs.Unmarshal(m, b)
}
func (m *CancelArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelArgs.Marshal(b, m, deterministic)
}
func (m *CancelArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelArgs.Merge(m, src)
}
func (m *CancelArgs) XXX_Size() int {
	return xxx_messageInfo_CancelArgs.Size(m)
}
func (m *CancelArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelArgs.DiscardUnknown(m)
}

var xxx_messageInfo_CancelArgs proto.InternalMessageInfo

func (m *CancelArgs) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *CancelArgs) GetSubscriptionId() uint32 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

type CancelReply struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResponseCode         string   `protobuf:"bytes,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelReply) Reset()         { *m = CancelReply{} }
func (m *CancelReply) String() string { return proto.CompactTextString(m) }
func (*CancelReply) ProtoMessage()    {}
func (*CancelReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c059edd071d94e03, []int{4}
}

func (m *CancelReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelReply.Unmarshal(m, b)
}
func (m *CancelReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelReply.Marshal(b, m, deterministic)
}
func (m *CancelReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelReply.Merge(m, src)
}
func (m *CancelReply) XXX_Size() int {
	return xxx_messageInfo_CancelReply.Size(m)
}
func (m *CancelReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelReply.DiscardUnknown(m)
}

var xxx_messageInfo_CancelReply proto.InternalMessageInfo

func (m *CancelReply) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *CancelReply) GetResponseCode() string {
	if m != nil {
		return m.ResponseCode
	}
	return ""
}

func (m *CancelReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Path)(nil), "huawei_dialin.Path")
	proto.RegisterType((*SubsArgs)(nil), "huawei_dialin.SubsArgs")
	proto.RegisterType((*SubsReply)(nil), "huawei_dialin.SubsReply")
	proto.RegisterType((*CancelArgs)(nil), "huawei_dialin.CancelArgs")
	proto.RegisterType((*CancelReply)(nil), "huawei_dialin.CancelReply")
}

func init() {
	proto.RegisterFile("proto/huawei-dialin/huawei-grpc-dialin.proto", fileDescriptor_c059edd071d94e03)
}

var fileDescriptor_c059edd071d94e03 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xba, 0xae, 0x6b, 0x6f, 0x3f, 0xd0, 0xcc, 0x03, 0x21, 0x12, 0x52, 0x94, 0x3d, 0x2c,
	0x0f, 0xac, 0xa0, 0xf1, 0x0b, 0xb6, 0xf2, 0xb0, 0x22, 0x21, 0x26, 0xc3, 0x7b, 0xe4, 0x24, 0x97,
	0xd4, 0x90, 0xd9, 0xc6, 0x76, 0x40, 0xfc, 0x12, 0xfe, 0x12, 0x7f, 0x88, 0x77, 0x54, 0x3b, 0x59,
	0x47, 0x89, 0x04, 0x6f, 0xbe, 0xe7, 0x9c, 0xdc, 0x7b, 0xcf, 0xb1, 0x03, 0xcf, 0x95, 0x96, 0x56,
	0xbe, 0xd8, 0x36, 0xec, 0x1b, 0xf2, 0x8b, 0x92, 0xb3, 0x9a, 0x8b, 0xae, 0xaa, 0xb4, 0x2a, 0x5a,
	0x68, 0xe5, 0x64, 0x64, 0xe1, 0x99, 0xcc, 0x83, 0x49, 0x04, 0xa3, 0x5b, 0x66, 0xb7, 0x84, 0xc0,
	0x48, 0x31, 0xbb, 0x0d, 0x83, 0x38, 0x48, 0xa7, 0xd4, 0x9d, 0x93, 0x5f, 0x01, 0x4c, 0xde, 0x37,
	0xb9, 0xb9, 0xd2, 0x95, 0x21, 0xcf, 0x00, 0x34, 0x7e, 0x69, 0xd0, 0xd8, 0x8c, 0x97, 0x4e, 0x36,
	0xa2, 0xd3, 0x16, 0xd9, 0x94, 0x24, 0x82, 0x09, 0x8a, 0x42, 0x96, 0x5c, 0x54, 0xe1, 0x30, 0x0e,
	0xd2, 0x05, 0xbd, 0xaf, 0xc9, 0x79, 0xdb, 0xfb, 0x38, 0x3e, 0x4a, 0x67, 0x97, 0x8f, 0x57, 0x7f,
	0x6c, 0xb0, 0xda, 0x8d, 0xf7, 0x03, 0xc9, 0x39, 0x3c, 0x32, 0xec, 0x4e, 0xd5, 0x98, 0x71, 0x61,
	0x51, 0x7f, 0x65, 0x75, 0x38, 0x76, 0x83, 0x96, 0x1e, 0xde, 0xb4, 0x28, 0xb9, 0x00, 0xb2, 0x45,
	0xa6, 0x6d, 0x8e, 0xcc, 0xee, 0xb5, 0x27, 0x4e, 0x7b, 0x7a, 0xcf, 0x3c, 0x94, 0x9b, 0x46, 0x29,
	0x8d, 0xc6, 0x64, 0x1a, 0xcb, 0x46, 0x94, 0x4c, 0xd8, 0x70, 0x12, 0x07, 0xe9, 0x84, 0x9e, 0x76,
	0x0c, 0xed, 0x88, 0xe4, 0x67, 0x00, 0xd3, 0x9d, 0x6f, 0x8a, 0xaa, 0xfe, 0xee, 0x96, 0x6a, 0x72,
	0x53, 0x68, 0xae, 0x2c, 0x97, 0xa2, 0x73, 0xbf, 0xa0, 0xcb, 0x87, 0xf0, 0xa6, 0x3c, 0x48, 0x68,
	0x78, 0x98, 0xd0, 0x19, 0x2c, 0x34, 0x1a, 0x25, 0x85, 0xc1, 0xac, 0x90, 0x25, 0x86, 0x47, 0x2e,
	0xea, 0x79, 0x07, 0xae, 0x65, 0x89, 0x24, 0x82, 0x93, 0x3b, 0x34, 0x86, 0x55, 0x18, 0x8e, 0xe2,
	0x20, 0x9d, 0xdf, 0x0c, 0x68, 0x07, 0x90, 0x33, 0x98, 0xb7, 0xc7, 0xec, 0x93, 0x91, 0x22, 0x3c,
	0xde, 0x7d, 0x7f, 0x33, 0xa0, 0xb3, 0x16, 0x7d, 0x63, 0xa4, 0xb8, 0x5e, 0xc0, 0xec, 0xad, 0x2f,
	0x5f, 0x33, 0xcb, 0x92, 0x0f, 0x00, 0x6b, 0x26, 0x0a, 0xac, 0xff, 0xe7, 0x0e, 0x7b, 0x9c, 0x0e,
	0xfb, 0x9c, 0x26, 0x9f, 0x61, 0xe6, 0xbb, 0xfa, 0x84, 0xfe, 0xd1, 0xf6, 0x2f, 0xe3, 0xc3, 0x1e,
	0xe3, 0xe1, 0xde, 0xb8, 0xcf, 0xa5, 0x2b, 0x2f, 0x7f, 0x04, 0xb0, 0xac, 0xe8, 0xed, 0x7a, 0x2d,
	0xc5, 0x47, 0x5e, 0xbd, 0x53, 0xa8, 0xc9, 0xb5, 0xbf, 0x9f, 0x42, 0xf3, 0x1c, 0xc9, 0x93, 0x83,
	0xf7, 0xd4, 0xbd, 0xd8, 0x28, 0xec, 0x21, 0xdc, 0xc2, 0xc9, 0xe0, 0x65, 0x40, 0xae, 0x60, 0xec,
	0x3d, 0x90, 0xa7, 0x07, 0xba, 0x7d, 0x60, 0x51, 0xd4, 0x4b, 0xb5, 0x4d, 0xf2, 0xb1, 0xfb, 0xa3,
	0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xac, 0x27, 0x35, 0x81, 0x03, 0x00, 0x00,
}
