// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sensors/huawei-kpi/huawei-kpi.proto

package huawei_kpi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kpi struct {
	KpiDatas             *Kpi_KpiDatas `protobuf:"bytes,1,opt,name=kpi_datas,json=kpi-datas,proto3" json:"kpi_datas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Kpi) Reset()         { *m = Kpi{} }
func (m *Kpi) String() string { return proto.CompactTextString(m) }
func (*Kpi) ProtoMessage()    {}
func (*Kpi) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48020f000133d48, []int{0}
}

func (m *Kpi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kpi.Unmarshal(m, b)
}
func (m *Kpi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kpi.Marshal(b, m, deterministic)
}
func (m *Kpi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kpi.Merge(m, src)
}
func (m *Kpi) XXX_Size() int {
	return xxx_messageInfo_Kpi.Size(m)
}
func (m *Kpi) XXX_DiscardUnknown() {
	xxx_messageInfo_Kpi.DiscardUnknown(m)
}

var xxx_messageInfo_Kpi proto.InternalMessageInfo

func (m *Kpi) GetKpiDatas() *Kpi_KpiDatas {
	if m != nil {
		return m.KpiDatas
	}
	return nil
}

type Kpi_KpiDatas struct {
	KpiData              []*Kpi_KpiDatas_KpiData `protobuf:"bytes,1,rep,name=kpi_data,json=kpi-data,proto3" json:"kpi_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Kpi_KpiDatas) Reset()         { *m = Kpi_KpiDatas{} }
func (m *Kpi_KpiDatas) String() string { return proto.CompactTextString(m) }
func (*Kpi_KpiDatas) ProtoMessage()    {}
func (*Kpi_KpiDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48020f000133d48, []int{0, 0}
}

func (m *Kpi_KpiDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kpi_KpiDatas.Unmarshal(m, b)
}
func (m *Kpi_KpiDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kpi_KpiDatas.Marshal(b, m, deterministic)
}
func (m *Kpi_KpiDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kpi_KpiDatas.Merge(m, src)
}
func (m *Kpi_KpiDatas) XXX_Size() int {
	return xxx_messageInfo_Kpi_KpiDatas.Size(m)
}
func (m *Kpi_KpiDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_Kpi_KpiDatas.DiscardUnknown(m)
}

var xxx_messageInfo_Kpi_KpiDatas proto.InternalMessageInfo

func (m *Kpi_KpiDatas) GetKpiData() []*Kpi_KpiDatas_KpiData {
	if m != nil {
		return m.KpiData
	}
	return nil
}

type Kpi_KpiDatas_KpiData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ModuleId             uint32   `protobuf:"varint,2,opt,name=module_id,json=module-id,proto3" json:"module_id,omitempty"`
	ModuleName           string   `protobuf:"bytes,3,opt,name=module_name,json=module-name,proto3" json:"module_name,omitempty"`
	SequenceId           uint32   `protobuf:"varint,4,opt,name=sequence_id,json=sequence-id,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kpi_KpiDatas_KpiData) Reset()         { *m = Kpi_KpiDatas_KpiData{} }
func (m *Kpi_KpiDatas_KpiData) String() string { return proto.CompactTextString(m) }
func (*Kpi_KpiDatas_KpiData) ProtoMessage()    {}
func (*Kpi_KpiDatas_KpiData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48020f000133d48, []int{0, 0, 0}
}

func (m *Kpi_KpiDatas_KpiData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kpi_KpiDatas_KpiData.Unmarshal(m, b)
}
func (m *Kpi_KpiDatas_KpiData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kpi_KpiDatas_KpiData.Marshal(b, m, deterministic)
}
func (m *Kpi_KpiDatas_KpiData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kpi_KpiDatas_KpiData.Merge(m, src)
}
func (m *Kpi_KpiDatas_KpiData) XXX_Size() int {
	return xxx_messageInfo_Kpi_KpiDatas_KpiData.Size(m)
}
func (m *Kpi_KpiDatas_KpiData) XXX_DiscardUnknown() {
	xxx_messageInfo_Kpi_KpiDatas_KpiData.DiscardUnknown(m)
}

var xxx_messageInfo_Kpi_KpiDatas_KpiData proto.InternalMessageInfo

func (m *Kpi_KpiDatas_KpiData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Kpi_KpiDatas_KpiData) GetModuleId() uint32 {
	if m != nil {
		return m.ModuleId
	}
	return 0
}

func (m *Kpi_KpiDatas_KpiData) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Kpi_KpiDatas_KpiData) GetSequenceId() uint32 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func init() {
	proto.RegisterType((*Kpi)(nil), "huawei_kpi.Kpi")
	proto.RegisterType((*Kpi_KpiDatas)(nil), "huawei_kpi.Kpi.KpiDatas")
	proto.RegisterType((*Kpi_KpiDatas_KpiData)(nil), "huawei_kpi.Kpi.KpiDatas.KpiData")
}

func init() {
	proto.RegisterFile("proto/sensors/huawei-kpi/huawei-kpi.proto", fileDescriptor_a48020f000133d48)
}

var fileDescriptor_a48020f000133d48 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc4, 0x20,
	0x18, 0x86, 0xc3, 0xf5, 0xa2, 0xed, 0x57, 0x5d, 0x98, 0xc8, 0xc5, 0x81, 0x38, 0xe1, 0x40, 0x2f,
	0x39, 0x13, 0x27, 0x47, 0xb7, 0xdb, 0xf8, 0x03, 0x0d, 0x0a, 0x89, 0x5f, 0xea, 0x15, 0x2c, 0x6d,
	0x1c, 0x9d, 0xfd, 0x69, 0xfe, 0x2b, 0x03, 0x05, 0x75, 0xb9, 0x81, 0xe4, 0xcd, 0xf3, 0x3d, 0x79,
	0x06, 0xe0, 0xce, 0x4f, 0x6e, 0x76, 0xfb, 0x60, 0xc7, 0xe0, 0xa6, 0xb0, 0x7f, 0x5d, 0xf4, 0x87,
	0x45, 0x39, 0x78, 0xfc, 0x37, 0xbb, 0xe4, 0x50, 0x58, 0x49, 0x3f, 0x78, 0xbc, 0xfd, 0xda, 0x40,
	0x75, 0xf4, 0x48, 0x1f, 0xa0, 0x19, 0x3c, 0xf6, 0x46, 0xcf, 0x3a, 0x30, 0xc2, 0x89, 0x68, 0x0f,
	0xac, 0xfb, 0xf3, 0xba, 0xe3, 0xfa, 0x9e, 0xe2, 0x5d, 0x45, 0x55, 0x26, 0x75, 0xf7, 0x4d, 0xa0,
	0x2e, 0x9c, 0x3e, 0x42, 0x5d, 0x22, 0x8c, 0xf0, 0x4a, 0xb4, 0x07, 0x7e, 0xae, 0x51, 0x86, 0xaa,
	0x4b, 0x6b, 0xf7, 0x09, 0x97, 0x19, 0x52, 0x0a, 0xdb, 0x1c, 0x21, 0xe2, 0x4a, 0xa5, 0x4d, 0x6f,
	0xa0, 0x39, 0x39, 0xb3, 0xbc, 0xd9, 0x1e, 0x0d, 0xdb, 0x70, 0x22, 0xae, 0x55, 0x06, 0x12, 0x0d,
	0xe5, 0xd0, 0xe6, 0xeb, 0xa8, 0x4f, 0x96, 0x55, 0x9c, 0x88, 0x46, 0x65, 0x24, 0x23, 0x8a, 0x46,
	0xb0, 0xef, 0x8b, 0x1d, 0x5f, 0x52, 0x61, 0x9b, 0x0a, 0xbf, 0x48, 0xa2, 0x79, 0xbe, 0x48, 0xdf,
	0x73, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x74, 0x9c, 0xb4, 0x7a, 0x4b, 0x01, 0x00, 0x00,
}
