// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sensors/huawei-emdi/huawei-emdi.proto

package huawei_emdi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Emdi struct {
	EmdiChannels         *Emdi_EmdiChannels  `protobuf:"bytes,1,opt,name=emdi_channels,json=emdi-channels,proto3" json:"emdi_channels,omitempty"`
	EmdiTelemReps        *Emdi_EmdiTelemReps `protobuf:"bytes,2,opt,name=emdi_telem_reps,json=emdi-telem-reps,proto3" json:"emdi_telem_reps,omitempty"`
	EmdiTelemRtps        *Emdi_EmdiTelemRtps `protobuf:"bytes,3,opt,name=emdi_telem_rtps,json=emdi-telem-rtps,proto3" json:"emdi_telem_rtps,omitempty"`
	OutTelemReps         *Emdi_OutTelemReps  `protobuf:"bytes,4,opt,name=out_telem_reps,json=out-telem-reps,proto3" json:"out_telem_reps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Emdi) Reset()         { *m = Emdi{} }
func (m *Emdi) String() string { return proto.CompactTextString(m) }
func (*Emdi) ProtoMessage()    {}
func (*Emdi) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0}
}

func (m *Emdi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi.Unmarshal(m, b)
}
func (m *Emdi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi.Marshal(b, m, deterministic)
}
func (m *Emdi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi.Merge(m, src)
}
func (m *Emdi) XXX_Size() int {
	return xxx_messageInfo_Emdi.Size(m)
}
func (m *Emdi) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi proto.InternalMessageInfo

func (m *Emdi) GetEmdiChannels() *Emdi_EmdiChannels {
	if m != nil {
		return m.EmdiChannels
	}
	return nil
}

func (m *Emdi) GetEmdiTelemReps() *Emdi_EmdiTelemReps {
	if m != nil {
		return m.EmdiTelemReps
	}
	return nil
}

func (m *Emdi) GetEmdiTelemRtps() *Emdi_EmdiTelemRtps {
	if m != nil {
		return m.EmdiTelemRtps
	}
	return nil
}

func (m *Emdi) GetOutTelemReps() *Emdi_OutTelemReps {
	if m != nil {
		return m.OutTelemReps
	}
	return nil
}

type Emdi_EmdiChannels struct {
	EmdiChannel          []*Emdi_EmdiChannels_EmdiChannel `protobuf:"bytes,1,rep,name=emdi_channel,json=emdi-channel,proto3" json:"emdi_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Emdi_EmdiChannels) Reset()         { *m = Emdi_EmdiChannels{} }
func (m *Emdi_EmdiChannels) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiChannels) ProtoMessage()    {}
func (*Emdi_EmdiChannels) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 0}
}

func (m *Emdi_EmdiChannels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiChannels.Unmarshal(m, b)
}
func (m *Emdi_EmdiChannels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiChannels.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiChannels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiChannels.Merge(m, src)
}
func (m *Emdi_EmdiChannels) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiChannels.Size(m)
}
func (m *Emdi_EmdiChannels) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiChannels.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiChannels proto.InternalMessageInfo

func (m *Emdi_EmdiChannels) GetEmdiChannel() []*Emdi_EmdiChannels_EmdiChannel {
	if m != nil {
		return m.EmdiChannel
	}
	return nil
}

type Emdi_EmdiChannels_EmdiChannel struct {
	ChannelName          string   `protobuf:"bytes,1,opt,name=channel_name,json=channel-name,proto3" json:"channel_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emdi_EmdiChannels_EmdiChannel) Reset()         { *m = Emdi_EmdiChannels_EmdiChannel{} }
func (m *Emdi_EmdiChannels_EmdiChannel) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiChannels_EmdiChannel) ProtoMessage()    {}
func (*Emdi_EmdiChannels_EmdiChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 0, 0}
}

func (m *Emdi_EmdiChannels_EmdiChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel.Unmarshal(m, b)
}
func (m *Emdi_EmdiChannels_EmdiChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiChannels_EmdiChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel.Merge(m, src)
}
func (m *Emdi_EmdiChannels_EmdiChannel) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel.Size(m)
}
func (m *Emdi_EmdiChannels_EmdiChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiChannels_EmdiChannel proto.InternalMessageInfo

func (m *Emdi_EmdiChannels_EmdiChannel) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

type Emdi_EmdiTelemReps struct {
	EmdiTelemRep         []*Emdi_EmdiTelemReps_EmdiTelemRep `protobuf:"bytes,1,rep,name=emdi_telem_rep,json=emdi-telem-rep,proto3" json:"emdi_telem_rep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Emdi_EmdiTelemReps) Reset()         { *m = Emdi_EmdiTelemReps{} }
func (m *Emdi_EmdiTelemReps) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiTelemReps) ProtoMessage()    {}
func (*Emdi_EmdiTelemReps) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 1}
}

func (m *Emdi_EmdiTelemReps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiTelemReps.Unmarshal(m, b)
}
func (m *Emdi_EmdiTelemReps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiTelemReps.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiTelemReps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiTelemReps.Merge(m, src)
}
func (m *Emdi_EmdiTelemReps) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiTelemReps.Size(m)
}
func (m *Emdi_EmdiTelemReps) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiTelemReps.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiTelemReps proto.InternalMessageInfo

func (m *Emdi_EmdiTelemReps) GetEmdiTelemRep() []*Emdi_EmdiTelemReps_EmdiTelemRep {
	if m != nil {
		return m.EmdiTelemRep
	}
	return nil
}

type Emdi_EmdiTelemReps_EmdiTelemRep struct {
	VrId                  uint32   `protobuf:"varint,1,opt,name=vr_id,json=vr-id,proto3" json:"vr_id,omitempty"`
	ChannelName           string   `protobuf:"bytes,2,opt,name=channel_name,json=channel-name,proto3" json:"channel_name,omitempty"`
	ChannelSourceAddress  string   `protobuf:"bytes,3,opt,name=channel_source_address,json=channel-source-address,proto3" json:"channel_source_address,omitempty"`
	ChannelGroupAddress   string   `protobuf:"bytes,4,opt,name=channel_group_address,json=channel-group-address,proto3" json:"channel_group_address,omitempty"`
	ChannelVpnType        uint32   `protobuf:"varint,5,opt,name=channel_vpn_type,json=channel-vpn-type,proto3" json:"channel_vpn_type,omitempty"`
	VpnName               string   `protobuf:"bytes,6,opt,name=vpn_name,json=vpn-name,proto3" json:"vpn_name,omitempty"`
	VlanId                uint32   `protobuf:"varint,7,opt,name=vlan_id,json=vlan-id,proto3" json:"vlan_id,omitempty"`
	VsiName               string   `protobuf:"bytes,8,opt,name=vsi_name,json=vsi-name,proto3" json:"vsi_name,omitempty"`
	BdId                  uint32   `protobuf:"varint,9,opt,name=bd_id,json=bd-id,proto3" json:"bd_id,omitempty"`
	ReportPeriod          uint32   `protobuf:"varint,10,opt,name=report_period,json=report-period,proto3" json:"report_period,omitempty"`
	ReportTime            uint64   `protobuf:"varint,11,opt,name=report_time,json=report-time,proto3" json:"report_time,omitempty"`
	TotalRecvPackets      uint64   `protobuf:"varint,12,opt,name=total_recv_packets,json=total-recv-packets,proto3" json:"total_recv_packets,omitempty"`
	TotalLossPackets      uint64   `protobuf:"varint,13,opt,name=total_loss_packets,json=total-loss-packets,proto3" json:"total_loss_packets,omitempty"`
	TotalDisorderdPackets uint64   `protobuf:"varint,14,opt,name=total_disorderd_packets,json=total-disorderd-packets,proto3" json:"total_disorderd_packets,omitempty"`
	MonitorPeriod         uint32   `protobuf:"varint,15,opt,name=monitor_period,json=monitor-period,proto3" json:"monitor_period,omitempty"`
	MonitorTime           uint64   `protobuf:"varint,16,opt,name=monitor_time,json=monitor-time,proto3" json:"monitor_time,omitempty"`
	WorstRecvPackets      uint64   `protobuf:"varint,17,opt,name=worst_recv_packets,json=worst-recv-packets,proto3" json:"worst_recv_packets,omitempty"`
	WorstLossPackets      uint64   `protobuf:"varint,18,opt,name=worst_loss_packets,json=worst-loss-packets,proto3" json:"worst_loss_packets,omitempty"`
	WorstDisorderdPackets uint64   `protobuf:"varint,19,opt,name=worst_disorderd_packets,json=worst-disorderd-packets,proto3" json:"worst_disorderd_packets,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) Reset()         { *m = Emdi_EmdiTelemReps_EmdiTelemRep{} }
func (m *Emdi_EmdiTelemReps_EmdiTelemRep) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiTelemReps_EmdiTelemRep) ProtoMessage()    {}
func (*Emdi_EmdiTelemReps_EmdiTelemRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 1, 0}
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep.Unmarshal(m, b)
}
func (m *Emdi_EmdiTelemReps_EmdiTelemRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiTelemReps_EmdiTelemRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep.Merge(m, src)
}
func (m *Emdi_EmdiTelemReps_EmdiTelemRep) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep.Size(m)
}
func (m *Emdi_EmdiTelemReps_EmdiTelemRep) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiTelemReps_EmdiTelemRep proto.InternalMessageInfo

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetVrId() uint32 {
	if m != nil {
		return m.VrId
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetChannelSourceAddress() string {
	if m != nil {
		return m.ChannelSourceAddress
	}
	return ""
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetChannelGroupAddress() string {
	if m != nil {
		return m.ChannelGroupAddress
	}
	return ""
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetChannelVpnType() uint32 {
	if m != nil {
		return m.ChannelVpnType
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetVpnName() string {
	if m != nil {
		return m.VpnName
	}
	return ""
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetVsiName() string {
	if m != nil {
		return m.VsiName
	}
	return ""
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetBdId() uint32 {
	if m != nil {
		return m.BdId
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetReportPeriod() uint32 {
	if m != nil {
		return m.ReportPeriod
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetReportTime() uint64 {
	if m != nil {
		return m.ReportTime
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetTotalRecvPackets() uint64 {
	if m != nil {
		return m.TotalRecvPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetTotalLossPackets() uint64 {
	if m != nil {
		return m.TotalLossPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetTotalDisorderdPackets() uint64 {
	if m != nil {
		return m.TotalDisorderdPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetMonitorPeriod() uint32 {
	if m != nil {
		return m.MonitorPeriod
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetMonitorTime() uint64 {
	if m != nil {
		return m.MonitorTime
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetWorstRecvPackets() uint64 {
	if m != nil {
		return m.WorstRecvPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetWorstLossPackets() uint64 {
	if m != nil {
		return m.WorstLossPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemReps_EmdiTelemRep) GetWorstDisorderdPackets() uint64 {
	if m != nil {
		return m.WorstDisorderdPackets
	}
	return 0
}

type Emdi_EmdiTelemRtps struct {
	EmdiTelemRtp         []*Emdi_EmdiTelemRtps_EmdiTelemRtp `protobuf:"bytes,1,rep,name=emdi_telem_rtp,json=emdi-telem-rtp,proto3" json:"emdi_telem_rtp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Emdi_EmdiTelemRtps) Reset()         { *m = Emdi_EmdiTelemRtps{} }
func (m *Emdi_EmdiTelemRtps) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiTelemRtps) ProtoMessage()    {}
func (*Emdi_EmdiTelemRtps) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 2}
}

func (m *Emdi_EmdiTelemRtps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiTelemRtps.Unmarshal(m, b)
}
func (m *Emdi_EmdiTelemRtps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiTelemRtps.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiTelemRtps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiTelemRtps.Merge(m, src)
}
func (m *Emdi_EmdiTelemRtps) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiTelemRtps.Size(m)
}
func (m *Emdi_EmdiTelemRtps) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiTelemRtps.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiTelemRtps proto.InternalMessageInfo

func (m *Emdi_EmdiTelemRtps) GetEmdiTelemRtp() []*Emdi_EmdiTelemRtps_EmdiTelemRtp {
	if m != nil {
		return m.EmdiTelemRtp
	}
	return nil
}

type Emdi_EmdiTelemRtps_EmdiTelemRtp struct {
	VrId                 uint32   `protobuf:"varint,1,opt,name=vr_id,json=vr-id,proto3" json:"vr_id,omitempty"`
	ChannelName          string   `protobuf:"bytes,2,opt,name=channel_name,json=channel-name,proto3" json:"channel_name,omitempty"`
	ChannelSourceAddress string   `protobuf:"bytes,3,opt,name=channel_source_address,json=channel-source-address,proto3" json:"channel_source_address,omitempty"`
	ChannelGroupAddress  string   `protobuf:"bytes,4,opt,name=channel_group_address,json=channel-group-address,proto3" json:"channel_group_address,omitempty"`
	ChannelVpnType       uint32   `protobuf:"varint,5,opt,name=channel_vpn_type,json=channel-vpn-type,proto3" json:"channel_vpn_type,omitempty"`
	VpnName              string   `protobuf:"bytes,6,opt,name=vpn_name,json=vpn-name,proto3" json:"vpn_name,omitempty"`
	VlanId               uint32   `protobuf:"varint,7,opt,name=vlan_id,json=vlan-id,proto3" json:"vlan_id,omitempty"`
	VsiName              string   `protobuf:"bytes,8,opt,name=vsi_name,json=vsi-name,proto3" json:"vsi_name,omitempty"`
	BdId                 uint32   `protobuf:"varint,9,opt,name=bd_id,json=bd-id,proto3" json:"bd_id,omitempty"`
	ReportPeriod         uint32   `protobuf:"varint,10,opt,name=report_period,json=report-period,proto3" json:"report_period,omitempty"`
	ReportTime           uint64   `protobuf:"varint,11,opt,name=report_time,json=report-time,proto3" json:"report_time,omitempty"`
	RecvPackets          uint64   `protobuf:"varint,12,opt,name=recv_packets,json=recv-packets,proto3" json:"recv_packets,omitempty"`
	LossPackets          uint64   `protobuf:"varint,13,opt,name=loss_packets,json=loss-packets,proto3" json:"loss_packets,omitempty"`
	DisorderdPackets     uint64   `protobuf:"varint,14,opt,name=disorderd_packets,json=disorderd-packets,proto3" json:"disorderd_packets,omitempty"`
	MonitorPeriod        uint32   `protobuf:"varint,15,opt,name=monitor_period,json=monitor-period,proto3" json:"monitor_period,omitempty"`
	MonitorTime          uint64   `protobuf:"varint,16,opt,name=monitor_time,json=monitor-time,proto3" json:"monitor_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) Reset()         { *m = Emdi_EmdiTelemRtps_EmdiTelemRtp{} }
func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) String() string { return proto.CompactTextString(m) }
func (*Emdi_EmdiTelemRtps_EmdiTelemRtp) ProtoMessage()    {}
func (*Emdi_EmdiTelemRtps_EmdiTelemRtp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 2, 0}
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp.Unmarshal(m, b)
}
func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp.Marshal(b, m, deterministic)
}
func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp.Merge(m, src)
}
func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) XXX_Size() int {
	return xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp.Size(m)
}
func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_EmdiTelemRtps_EmdiTelemRtp proto.InternalMessageInfo

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetVrId() uint32 {
	if m != nil {
		return m.VrId
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetChannelSourceAddress() string {
	if m != nil {
		return m.ChannelSourceAddress
	}
	return ""
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetChannelGroupAddress() string {
	if m != nil {
		return m.ChannelGroupAddress
	}
	return ""
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetChannelVpnType() uint32 {
	if m != nil {
		return m.ChannelVpnType
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetVpnName() string {
	if m != nil {
		return m.VpnName
	}
	return ""
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetVsiName() string {
	if m != nil {
		return m.VsiName
	}
	return ""
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetBdId() uint32 {
	if m != nil {
		return m.BdId
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetReportPeriod() uint32 {
	if m != nil {
		return m.ReportPeriod
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetReportTime() uint64 {
	if m != nil {
		return m.ReportTime
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetRecvPackets() uint64 {
	if m != nil {
		return m.RecvPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetLossPackets() uint64 {
	if m != nil {
		return m.LossPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetDisorderdPackets() uint64 {
	if m != nil {
		return m.DisorderdPackets
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetMonitorPeriod() uint32 {
	if m != nil {
		return m.MonitorPeriod
	}
	return 0
}

func (m *Emdi_EmdiTelemRtps_EmdiTelemRtp) GetMonitorTime() uint64 {
	if m != nil {
		return m.MonitorTime
	}
	return 0
}

type Emdi_OutTelemReps struct {
	OutTelemRep          []*Emdi_OutTelemReps_OutTelemRep `protobuf:"bytes,1,rep,name=out_telem_rep,json=out-telem-rep,proto3" json:"out_telem_rep,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *Emdi_OutTelemReps) Reset()         { *m = Emdi_OutTelemReps{} }
func (m *Emdi_OutTelemReps) String() string { return proto.CompactTextString(m) }
func (*Emdi_OutTelemReps) ProtoMessage()    {}
func (*Emdi_OutTelemReps) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 3}
}

func (m *Emdi_OutTelemReps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_OutTelemReps.Unmarshal(m, b)
}
func (m *Emdi_OutTelemReps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_OutTelemReps.Marshal(b, m, deterministic)
}
func (m *Emdi_OutTelemReps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_OutTelemReps.Merge(m, src)
}
func (m *Emdi_OutTelemReps) XXX_Size() int {
	return xxx_messageInfo_Emdi_OutTelemReps.Size(m)
}
func (m *Emdi_OutTelemReps) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_OutTelemReps.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_OutTelemReps proto.InternalMessageInfo

func (m *Emdi_OutTelemReps) GetOutTelemRep() []*Emdi_OutTelemReps_OutTelemRep {
	if m != nil {
		return m.OutTelemRep
	}
	return nil
}

type Emdi_OutTelemReps_OutTelemRep struct {
	VrId                  uint32   `protobuf:"varint,1,opt,name=vr_id,json=vr-id,proto3" json:"vr_id,omitempty"`
	ChannelName           string   `protobuf:"bytes,2,opt,name=channel_name,json=channel-name,proto3" json:"channel_name,omitempty"`
	SlotId                string   `protobuf:"bytes,3,opt,name=slot_id,json=slot-id,proto3" json:"slot_id,omitempty"`
	ChannelSourceAddress  string   `protobuf:"bytes,4,opt,name=channel_source_address,json=channel-source-address,proto3" json:"channel_source_address,omitempty"`
	ChannelGroupAddress   string   `protobuf:"bytes,5,opt,name=channel_group_address,json=channel-group-address,proto3" json:"channel_group_address,omitempty"`
	ChannelVpnType        uint32   `protobuf:"varint,6,opt,name=channel_vpn_type,json=channel-vpn-type,proto3" json:"channel_vpn_type,omitempty"`
	VpnName               string   `protobuf:"bytes,7,opt,name=vpn_name,json=vpn-name,proto3" json:"vpn_name,omitempty"`
	InterfaceName         string   `protobuf:"bytes,8,opt,name=interface_name,json=interface-name,proto3" json:"interface_name,omitempty"`
	ReportPeriod          uint32   `protobuf:"varint,9,opt,name=report_period,json=report-period,proto3" json:"report_period,omitempty"`
	ReportTime            uint64   `protobuf:"varint,10,opt,name=report_time,json=report-time,proto3" json:"report_time,omitempty"`
	TotalRecvPackets      uint64   `protobuf:"varint,11,opt,name=total_recv_packets,json=total-recv-packets,proto3" json:"total_recv_packets,omitempty"`
	TotalLossPackets      uint64   `protobuf:"varint,12,opt,name=total_loss_packets,json=total-loss-packets,proto3" json:"total_loss_packets,omitempty"`
	TotalDisorderdPackets uint64   `protobuf:"varint,13,opt,name=total_disorderd_packets,json=total-disorderd-packets,proto3" json:"total_disorderd_packets,omitempty"`
	MonitorPeriod         uint32   `protobuf:"varint,14,opt,name=monitor_period,json=monitor-period,proto3" json:"monitor_period,omitempty"`
	MonitorTime           uint64   `protobuf:"varint,15,opt,name=monitor_time,json=monitor-time,proto3" json:"monitor_time,omitempty"`
	WorstRecvPackets      uint64   `protobuf:"varint,16,opt,name=worst_recv_packets,json=worst-recv-packets,proto3" json:"worst_recv_packets,omitempty"`
	WorstLossPackets      uint64   `protobuf:"varint,17,opt,name=worst_loss_packets,json=worst-loss-packets,proto3" json:"worst_loss_packets,omitempty"`
	WorstDisorderdPackets uint64   `protobuf:"varint,18,opt,name=worst_disorderd_packets,json=worst-disorderd-packets,proto3" json:"worst_disorderd_packets,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Emdi_OutTelemReps_OutTelemRep) Reset()         { *m = Emdi_OutTelemReps_OutTelemRep{} }
func (m *Emdi_OutTelemReps_OutTelemRep) String() string { return proto.CompactTextString(m) }
func (*Emdi_OutTelemReps_OutTelemRep) ProtoMessage()    {}
func (*Emdi_OutTelemReps_OutTelemRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f1f803ee628ebbd, []int{0, 3, 0}
}

func (m *Emdi_OutTelemReps_OutTelemRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep.Unmarshal(m, b)
}
func (m *Emdi_OutTelemReps_OutTelemRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep.Marshal(b, m, deterministic)
}
func (m *Emdi_OutTelemReps_OutTelemRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep.Merge(m, src)
}
func (m *Emdi_OutTelemReps_OutTelemRep) XXX_Size() int {
	return xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep.Size(m)
}
func (m *Emdi_OutTelemReps_OutTelemRep) XXX_DiscardUnknown() {
	xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep.DiscardUnknown(m)
}

var xxx_messageInfo_Emdi_OutTelemReps_OutTelemRep proto.InternalMessageInfo

func (m *Emdi_OutTelemReps_OutTelemRep) GetVrId() uint32 {
	if m != nil {
		return m.VrId
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetSlotId() string {
	if m != nil {
		return m.SlotId
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetChannelSourceAddress() string {
	if m != nil {
		return m.ChannelSourceAddress
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetChannelGroupAddress() string {
	if m != nil {
		return m.ChannelGroupAddress
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetChannelVpnType() uint32 {
	if m != nil {
		return m.ChannelVpnType
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetVpnName() string {
	if m != nil {
		return m.VpnName
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetReportPeriod() uint32 {
	if m != nil {
		return m.ReportPeriod
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetReportTime() uint64 {
	if m != nil {
		return m.ReportTime
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetTotalRecvPackets() uint64 {
	if m != nil {
		return m.TotalRecvPackets
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetTotalLossPackets() uint64 {
	if m != nil {
		return m.TotalLossPackets
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetTotalDisorderdPackets() uint64 {
	if m != nil {
		return m.TotalDisorderdPackets
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetMonitorPeriod() uint32 {
	if m != nil {
		return m.MonitorPeriod
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetMonitorTime() uint64 {
	if m != nil {
		return m.MonitorTime
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetWorstRecvPackets() uint64 {
	if m != nil {
		return m.WorstRecvPackets
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetWorstLossPackets() uint64 {
	if m != nil {
		return m.WorstLossPackets
	}
	return 0
}

func (m *Emdi_OutTelemReps_OutTelemRep) GetWorstDisorderdPackets() uint64 {
	if m != nil {
		return m.WorstDisorderdPackets
	}
	return 0
}

func init() {
	proto.RegisterType((*Emdi)(nil), "huawei_emdi.Emdi")
	proto.RegisterType((*Emdi_EmdiChannels)(nil), "huawei_emdi.Emdi.EmdiChannels")
	proto.RegisterType((*Emdi_EmdiChannels_EmdiChannel)(nil), "huawei_emdi.Emdi.EmdiChannels.EmdiChannel")
	proto.RegisterType((*Emdi_EmdiTelemReps)(nil), "huawei_emdi.Emdi.EmdiTelemReps")
	proto.RegisterType((*Emdi_EmdiTelemReps_EmdiTelemRep)(nil), "huawei_emdi.Emdi.EmdiTelemReps.EmdiTelemRep")
	proto.RegisterType((*Emdi_EmdiTelemRtps)(nil), "huawei_emdi.Emdi.EmdiTelemRtps")
	proto.RegisterType((*Emdi_EmdiTelemRtps_EmdiTelemRtp)(nil), "huawei_emdi.Emdi.EmdiTelemRtps.EmdiTelemRtp")
	proto.RegisterType((*Emdi_OutTelemReps)(nil), "huawei_emdi.Emdi.OutTelemReps")
	proto.RegisterType((*Emdi_OutTelemReps_OutTelemRep)(nil), "huawei_emdi.Emdi.OutTelemReps.OutTelemRep")
}

func init() {
	proto.RegisterFile("proto/sensors/huawei-emdi/huawei-emdi.proto", fileDescriptor_7f1f803ee628ebbd)
}

var fileDescriptor_7f1f803ee628ebbd = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x56, 0xda, 0xfc, 0x34, 0xc7, 0x76, 0xda, 0xcc, 0xed, 0xed, 0xb5, 0xbc, 0xb8, 0x44, 0x11,
	0xaa, 0xaa, 0xd2, 0x49, 0x45, 0x41, 0x88, 0x3d, 0x14, 0x89, 0x0d, 0x20, 0xab, 0x7b, 0xcb, 0x8d,
	0x07, 0x6a, 0x91, 0x78, 0xac, 0x99, 0x49, 0x2a, 0x9e, 0x80, 0x35, 0x3c, 0x0f, 0x8f, 0xc1, 0x3b,
	0x20, 0xf1, 0x08, 0xac, 0xd0, 0xcc, 0x78, 0xdc, 0x71, 0xdc, 0xb4, 0x49, 0x11, 0x12, 0x0b, 0x36,
	0x51, 0xe6, 0x7c, 0xdf, 0x77, 0x74, 0xbe, 0x99, 0x73, 0x74, 0x0c, 0x0f, 0x72, 0x46, 0x05, 0x3d,
	0xe6, 0x24, 0xe3, 0x94, 0xf1, 0xe3, 0x8b, 0x59, 0x7c, 0x49, 0x52, 0x4c, 0xa6, 0x49, 0x6a, 0xff,
	0x1f, 0x29, 0x16, 0x72, 0x74, 0x28, 0x92, 0xa1, 0xe1, 0xb7, 0x3d, 0x68, 0x9e, 0x4e, 0x93, 0x14,
	0x3d, 0x07, 0x4f, 0x06, 0xa2, 0xf1, 0x45, 0x9c, 0x65, 0x64, 0xc2, 0xfd, 0xc6, 0xa0, 0x71, 0xe0,
	0x9c, 0xfc, 0x3f, 0xb2, 0xd8, 0xa3, 0x53, 0xf3, 0xf3, 0xac, 0x60, 0x85, 0x4a, 0x84, 0x8d, 0x08,
	0xbd, 0x84, 0x6d, 0x95, 0x45, 0x90, 0x09, 0x99, 0x46, 0x8c, 0xe4, 0xdc, 0xdf, 0x50, 0x79, 0xee,
	0x5d, 0x9f, 0xe7, 0x4c, 0xf2, 0x42, 0x92, 0xf3, 0x50, 0xe9, 0xb0, 0xd2, 0x61, 0xa9, 0x5b, 0x4c,
	0x25, 0x72, 0xee, 0x6f, 0xde, 0x9e, 0x4a, 0x2c, 0xa6, 0x12, 0x39, 0x47, 0x2f, 0xa0, 0x47, 0x67,
	0xc2, 0x2e, 0xaa, 0xb9, 0xcc, 0xdc, 0xeb, 0x99, 0xb8, 0xaa, 0x49, 0xaa, 0xac, 0x92, 0x82, 0x4f,
	0x0d, 0x70, 0x6d, 0xf7, 0xe8, 0x15, 0xb8, 0xf6, 0xa5, 0xf9, 0x8d, 0xc1, 0xe6, 0x81, 0x73, 0x72,
	0x78, 0xf3, 0x9d, 0xd9, 0x87, 0xd0, 0xb5, 0xef, 0x2f, 0x78, 0x08, 0x8e, 0x05, 0xa2, 0x21, 0xb8,
	0x05, 0x12, 0x65, 0xf1, 0x94, 0xa8, 0x27, 0xe9, 0x86, 0x26, 0x86, 0x65, 0x2c, 0xf8, 0xd1, 0x06,
	0xaf, 0x72, 0x93, 0xe8, 0x0c, 0x7a, 0xd5, 0x37, 0x28, 0xca, 0x3a, 0xba, 0xe5, 0x09, 0x2a, 0xa7,
	0xb0, 0x57, 0x7d, 0x8f, 0xe0, 0x73, 0x5b, 0x7b, 0x37, 0x04, 0xb4, 0x0b, 0xad, 0x39, 0x8b, 0xd2,
	0x44, 0x55, 0xe5, 0x85, 0xad, 0x39, 0xc3, 0x69, 0x52, 0x2b, 0x79, 0xa3, 0x5e, 0x32, 0x7a, 0x02,
	0x7b, 0x86, 0xc3, 0xe9, 0x8c, 0x8d, 0x49, 0x14, 0x27, 0x09, 0x23, 0x5c, 0x3f, 0x70, 0x37, 0x34,
	0x28, 0xd6, 0x28, 0x2e, 0x50, 0xf4, 0x18, 0xfe, 0x35, 0xba, 0x77, 0x8c, 0xce, 0xf2, 0x52, 0xd6,
	0x54, 0x32, 0x03, 0x62, 0x05, 0x96, 0xaa, 0x43, 0xd8, 0x31, 0xaa, 0x79, 0x9e, 0x45, 0xe2, 0x43,
	0x4e, 0xfc, 0x96, 0x2a, 0xd9, 0xc4, 0xf1, 0x3c, 0xcf, 0xb0, 0x8c, 0xa3, 0x00, 0xb6, 0x24, 0x47,
	0x55, 0xde, 0x56, 0x49, 0xe5, 0x59, 0x57, 0xed, 0x43, 0x67, 0x3e, 0x89, 0x33, 0xe9, 0xb8, 0xa3,
	0xe4, 0xea, 0x28, 0x3d, 0x4b, 0x15, 0x4f, 0xb5, 0x6a, 0xab, 0x50, 0xf1, 0x54, 0xab, 0x76, 0xa1,
	0x75, 0x9e, 0x48, 0x4d, 0x57, 0xdf, 0xd2, 0x79, 0x22, 0x15, 0xf7, 0xc1, 0x63, 0x24, 0xa7, 0x4c,
	0x44, 0x39, 0x61, 0x29, 0x4d, 0x7c, 0x50, 0x68, 0x11, 0xc4, 0x3a, 0x88, 0x06, 0xe0, 0x14, 0x2c,
	0x91, 0x4e, 0x89, 0xef, 0x0c, 0x1a, 0x07, 0xcd, 0xb0, 0x08, 0x61, 0x19, 0x42, 0x23, 0x40, 0x82,
	0x8a, 0x78, 0x12, 0x31, 0x32, 0x9e, 0x47, 0x79, 0x3c, 0x7e, 0x4f, 0x04, 0xf7, 0x5d, 0x45, 0xd4,
	0x08, 0x96, 0x08, 0x2e, 0x90, 0x2b, 0xfe, 0x84, 0x72, 0x5e, 0xf2, 0x3d, 0x9b, 0x2f, 0x91, 0x92,
	0xff, 0x14, 0xfe, 0xd3, 0xfc, 0x24, 0xe5, 0x94, 0x25, 0x84, 0x25, 0xa5, 0xa8, 0xa7, 0x44, 0x1a,
	0xc6, 0x25, 0x5c, 0x2a, 0xf7, 0xa1, 0x37, 0xa5, 0x59, 0x2a, 0x28, 0x33, 0x16, 0xb7, 0x95, 0x45,
	0x13, 0x35, 0x1e, 0x87, 0xe0, 0x1a, 0x9e, 0x32, 0xb9, 0xa3, 0xd2, 0x9a, 0x58, 0xe9, 0xf2, 0x92,
	0x32, 0x2e, 0xaa, 0x2e, 0xfb, 0xba, 0x6a, 0x85, 0xd4, 0x5c, 0x6a, 0x7e, 0xc5, 0x25, 0xb2, 0xf9,
	0x8b, 0x2e, 0x35, 0xbf, 0xee, 0xf2, 0x1f, 0xed, 0x52, 0x8b, 0x6a, 0x2e, 0x83, 0x2f, 0x2d, 0x7b,
	0xf8, 0x44, 0x7d, 0xf8, 0xc4, 0x4a, 0xc3, 0x27, 0x2a, 0xc3, 0x27, 0x16, 0x86, 0x4f, 0xe4, 0xc1,
	0xd7, 0xa6, 0x3d, 0x7c, 0xe2, 0xef, 0xf0, 0xfd, 0x09, 0xc3, 0x37, 0x04, 0xf7, 0x9a, 0xb1, 0x73,
	0x2b, 0xad, 0x38, 0x04, 0xf7, 0x9a, 0x51, 0x73, 0x2b, 0xed, 0x77, 0x04, 0xfd, 0x65, 0xe3, 0xd5,
	0xff, 0xad, 0x83, 0x15, 0x7c, 0x6f, 0x83, 0x6b, 0x2f, 0x3c, 0xf4, 0x06, 0xbc, 0xca, 0xa2, 0x5c,
	0xbe, 0xd0, 0x6c, 0x99, 0x7d, 0x08, 0xbd, 0xca, 0xce, 0x0c, 0x3e, 0xb6, 0xc1, 0xb1, 0xe0, 0x5f,
	0x68, 0x5c, 0x1f, 0x3a, 0x7c, 0x42, 0x85, 0xd4, 0xea, 0x4e, 0x55, 0x47, 0xa9, 0x5e, 0xde, 0xd2,
	0xcd, 0xbb, 0xb5, 0x74, 0x6b, 0xdd, 0x96, 0x6e, 0xaf, 0xd0, 0xd2, 0x9d, 0x85, 0x96, 0xde, 0x87,
	0x5e, 0x9a, 0x09, 0xc2, 0xde, 0xc6, 0x63, 0x62, 0xb7, 0xef, 0x55, 0x54, 0xf3, 0x6a, 0xed, 0xda,
	0x5d, 0xa1, 0x5d, 0x61, 0xd5, 0x5d, 0xe1, 0xac, 0xb9, 0x2b, 0xdc, 0xbb, 0xec, 0x0a, 0x6f, 0xdd,
	0x5d, 0xd1, 0x5b, 0xa9, 0xa5, 0xb7, 0x57, 0xde, 0x15, 0x3b, 0x6b, 0xee, 0x8a, 0xfe, 0x5d, 0x76,
	0x05, 0xba, 0x71, 0x57, 0x9c, 0xb7, 0xd5, 0xd7, 0xf7, 0xa3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x95, 0x9e, 0x6b, 0x23, 0xac, 0x0b, 0x00, 0x00,
}
